### ISSUE TITLE
Notion links that open in browser rather than Notion desktop app

### ISSUE THREAD

**Issue by louaymd** [dvanoni/notero#148] opened 2022-10-05 14:34 UTC
This is a very minor, nonurgent but hopefully easy-to-implement request: I’d like the attachments added to synced items in Zotero to open Notion in the browser, rather than be local links to the Notion desktop app.

It should be as simple as removing the “notion://“ part of the current hyperlinks. For those who have a workspace name assigned, you would also need to add “{workspace_name}/“ after notion.so/. 

So for example, this link would be changed from: 
notion://www.notion.so/Wood-et-al-2019-b26e3927eee74a3583134ebed285efa1
to
https://www.notion.so/{workspace_name}/Wood-et-al-2019-b26e3927eee74a3583134ebed285efa1.

Again consider it a low-priority but low-effort request. I would do it myself if building my own notero version had worked! 
(and an obligatory ‘thank you’ to the excellent work you’ve done here dvanoni)

**Comment by dvanoni** [comment] 2022-11-13 01:40
@louaymd, thanks for the feedback! I'm going to mark this as a duplicate of #53. Though, I like the title you used, so I'm going to copy that over to the other issue. Please follow along there!

**Closed by dvanoni** 2022-11-13 01:40 UTC
Labels: enhancement
