### ISSUE TITLE
Multiple Zotero collection map to multiple Notion database

### ISSUE THREAD

**Issue by yingpublic** [dvanoni/notero#124] opened 2022-09-04 11:18 UTC
Thank you for providing Notero add-ons! 

I have several collection in my Zotero for quite different topic that I don't want to mix it together. I would like to know if you can add a feature so that we can have a unique Integration token and Database ID (Notion database) for each collection that I would like to update separately. Or maybe I just missed an existing feature please let me know! Thank you so much for your effort!

**Comment by heyyiluo** [comment] 2022-09-07 14:36
I am in the same situation. Thanks for the wonderful Notero add-ones. Would be great if it is possible the sync each collection separately. Thanks again!

**Comment by dvanoni** [comment] 2022-11-14 00:49
Thanks for the feedback, everyone! I'm going to close this issue as a duplicate of #119. Please feel free to follow along there and add any additional input.

**Closed by dvanoni** 2022-11-14 00:49 UTC
Labels: enhancement
