### ISSUE TITLE
Sync annotations and notes

### ISSUE THREAD

**Issue by eelshaikh** [dvanoni/notero#111] opened 2022-08-21 16:40 UTC
Hi,

I'd love a field that pulls the notes from a Zotero entry into a column in a Notero database. Currently, I have to manually copy and paste annotations. This feature would absolutely supercharge my productivity. Please let me know how I can supports its development!

**Comment by dvanoni** [comment] 2022-08-21 19:03
Hi @eelshaikh, thanks for sharing your feedback! I'm going to make this as a duplicate of #4, so feel free to add any additional comments there.

**Closed by dvanoni** 2022-08-21 19:03 UTC
Labels: enhancement
