### ISSUE TITLE
Type Error: ‘fetch’ called on an object that does not implement interface Window

### ISSUE THREAD

**Issue by zny3108** [dvanoni/notero#171] opened 2022-11-15 13:01 UTC
When I finished all steps you described and tried to add some files,  something wrong occurred. 
![Screenshot_20221115_085359](https://user-images.githubusercontent.com/52792249/201925773-56cda099-a632-4dc5-abcd-cdaae87ebfea.png)
Please help me, thx!!!

**Comment by zny3108** [comment] 2022-11-21 10:42
My Zotero version is 6.0.18, and the Notero version is 0.4.0, and I can show you all add-ons in my Zotero, maybe this would help you more.
thank you!
![image](https://user-images.githubusercontent.com/52792249/203030490-7802330b-b2a8-4c8c-b3fb-fcdbb1762bfb.png)

**Comment by zny3108** [comment] 2022-11-21 11:09
hello, I  just fixed this problem. I found if I disabled "chartero" in add-ons, the Notero could work properly. Although your Notero is more significant than it (lol), but I also  hope I can use both in my daily work. But if you found this bug would spend much of your time, please miss this bug and this idea(lol).

**Comment by dvanoni** [comment] 2022-11-22 05:53
@zny3108, thanks for discovering the source of the issue! I see that the same error message you encountered is mentioned in https://github.com/volatile-static/Chartero/issues/7#issuecomment-1285746632.

I took a quick look at the Chatero code but didn't find anything that immediately stood out to me as being the cause of the issue. I'd need to dig in deeper to figure out what's going on.

**Comment by dvanoni** [comment] 2023-10-29 01:02
This may have been fixed in #340 as we now use a different approach for retrieving the window object to call `fetch` on.

I'm going to close this issue for now, but feel free to reopen it if this continues to be a problem.

**Closed by dvanoni** 2023-10-29 01:02 UTC
