### ISSUE TITLE
Add 'Select All New Folders' option for automatic future folder synchronization

### ISSUE THREAD

**Issue by menelic** [dvanoni/notero#374] opened 2023-11-03 16:23 UTC
**Is your feature request related to a problem? Please describe.**
Thank you for Notero, its a key part of our workflow!

The user must manually select each folder to choose which ones are automatically synced. This means the user has to remember to go back and check the new box anytime a new collection or folder is created in Zotero.

**Describe the solution you'd like**

Please add an option to select "All Folders" so that synchronization applies to any new folders created in the library going forward?

Automatically syncing all current and future folders would improve the user experience by avoiding the need to manually select each new one. Let me know if any other details could help explain or resolve this issue. Thank you for your consideration!

**Additional context**
![image](https://github.com/dvanoni/notero/assets/5934115/5a63bc4c-7573-4da0-bf00-6f5ead488bf7)

**Comment by dvanoni** [comment] 2023-11-03 17:42
Hi @menelic, thanks for the feature request! I agree this would be a great feature to have. I believe this is already captured in #63, so I'm going to close this one, but thanks for the nice description!

**Comment by dvanoni** [comment] 2023-11-03 17:42
Duplicate of #63

**Closed** 2023-11-03 17:43 UTC
Labels: duplicate, enhancement

**Comment by menelic** [comment] 2023-11-03 22:24
Hi, thanks for the swift reply! I think this issue is not a duplicate of #63.The way I understand #63 its just about syncing the whole collection once, whereas my request is about syncing all current and _future_ folders. This is particularly important for usage in a team, where several team members work with a shared collection to which they add folders with sources.

**Comment by dvanoni** [comment] 2023-11-03 22:49
Hi @menelic, thanks for the reply!

Your description here is my understanding of #63, so that issue could probably use an update to make it clearer that these are indeed the same concept. I should probably also clarify that what I call a "collection" in Notero is what's more commonly thought of as the "folders" in Zotero. I used the term "collection" because that's what Zotero calls them.

To hopefully clarify my idea behind this, what I'm thinking is adding a toggle into the Notero preferences called something like "Sync all collections." If you have that enabled, then the current table of collections won't show up at all. There wouldn't be a need for it since all items would sync regardless of which collections they're added to. If the "Sync all collections" toggle is disabled, then the table will appear so that you can select individual collections to enable syncing for.

Does that sound like it's what you're hoping for?

**Comment by menelic** [comment] 2024-09-30 11:44
yes, this description and the additional quite added to #63 captures it well, thank you.
