### ISSUE TITLE
Synchronize multiple notion pages

### ISSUE THREAD

**Issue by med1104** [dvanoni/notero#291] opened 2023-07-13 15:24 UTC
Es posible sincronizar dos colecciones en dos paginas de notion distintas? Se me ocurre que la solución seria duplicar la extencion Notero y configurar cada una con su respectiva pagina de Notion. Pero no se si esto pueda generar algun cruce. 

I say this because I have different themes in Zotero and I want to bring them to tables in notion separately depending on the project I'm working on.

**Comment by dvanoni** [comment] 2023-07-14 03:23
Hi @med1104, it sounds like this might be the same feature request described in #119. Does that one capture what you're looking for?

As for duplicating the Notero extension, it would require several tweaks to make this approach work so that multiple instances of the extension could manage data separately. I wouldn't recommend this approach because it would start to get messy. I do hope to build proper support for multiple databases in the future.

**Comment by dvanoni** [comment] 2023-07-31 00:34
Duplicate of #119

**Closed** 2023-07-31 00:35 UTC
Labels: enhancement
