### ISSUE TITLE
Syncing problems 

### ISSUE THREAD

**Issue by carolinecogueto** [dvanoni/notero#147] opened 2022-10-05 09:52 UTC
I succesfully integrated my references from Zotero into Notion, but new references added to my Zotero, or modifications to references done in Zotero (e.g., adding the name of the authors, modifyng doc type) are not syncing automatically... any clue ? I read existing posts but could not find a solution.  

Expected behavior: references added to my zotero integrated folders and modifications done to them are automatically synced into Notion.

**Comment by NonieRodgers** [comment] 2022-10-05 13:27
I'm having the exact same issue, got it to work yesterday but it's not working today! I've tried disconnecting everything and re-connecting and it's still not working...

**Comment by carolinecogueto** [comment] 2022-10-09 20:16
I could get around the problem by simply moving the new references that do not sync automatically to another folder  - no need delete them from the synced folder and bring them back, just clicking and draging them to another folder is enough to trigger syncing!)

**Comment by GabelSpitzer** [comment] 2022-10-28 07:37
I am also having problems with this: it was automatically synching until last week and suddenly stopped

**Comment by Spokhim** [comment] 2022-10-31 04:32
Same as GabelSpitzer.  It was automatically syncing correctly up until recently.  
The only thing I can think of is that I upgraded my Mac's OS recently...

**Comment by bezirganyan** [comment] 2022-10-31 09:53
I also have the same problem. Everything was working on Friday, now 2 days later nothing is syncing. Unlike @Spokhim I didn't update or upgrade anything, so I doubt upgrading Mac would cause the issue. 

I am on Ubuntu 22.04.

**Comment by NonieRodgers** [comment] 2022-10-31 10:29
I've also found a workaround that may help, in Zotero click on the tags and if there is no tag saying "notion" then it will not sync, try typing in your own tag and this should initiate the sync!

I seem to be getting intermittent syncing, where sometimes its automated, and other times I have to edit the tags to make it work.

Hope this helps

**Comment by hannah-v-91** [comment] 2022-11-11 13:13
I am having the same issue.

**Comment by dvanoni** [comment] 2022-11-15 06:01
This seems like a tricky one to nail down. On my computer, I've both updated macOS and have the Zotero LibreOffice Integration plugin enabled, and yet I don't appear to be running into any issue with syncing.

I may need to add some more detailed logging into the plugin to help me narrow down the cause of these syncing issues.

**Comment by dtn1984** [comment] 2023-01-19 12:05
@dvanoni I believe I solved my issue related to not synching in a different way.

I use Windows + Office, so I do not have the LibreOffice issue others report, but I faced the same problem of my zotero library not synching with Notion.

I followed @NonieRodgers recommendations about tagging Zotero entries with "notion" and that works. But when I tag only one entry, all the entries in the collection are sent to Notion. Just reporting this in case you have time to check it.

Thank you for your effort!

**Comment by dvanoni** [comment] 2023-01-21 05:31
@dtn1984, thanks for sharing! That's very interesting behavior. I still need to dig into this because I'm not sure what's going on. 🤔 

In the meantime, if you're still having issues with syncing, there's a recently-released feature that can maybe help. Instead of having to add the "notion" tag, you can select items or an entire collection and right-click on it to bring up the context menu. In the menu, there's now a "Sync to Notion" option that you can use. Hopefully that makes things a bit easier!

**Comment by premsa** [comment] 2023-03-20 11:49
The "Sync to Notion" Option fixed it for me! Thanks

**Comment by dtn1984** [comment] 2023-04-12 15:14
@lauraengl I faced similar things with Zutilo where it just vanished out of the software. What I do is disable and reenable the add-on.

**Comment by lauraengl** [comment] 2023-04-12 17:14
@dvanoni I'm also using a Mac but , what I doesn't get is that sometimes it does de sync fine and sometimes not. But I did What DTN1984 suggested and fixed the problem of the "sync to notion" appearance in the context menu. So now, I'm able to manually sync the ref that do not sync automatically...
@dtn1984 thanks a lot, I did it and it's back ! I don't know for how long but it's back!

**Comment by maria-antoniak** [comment] 2023-04-13 16:41
I'm facing the same issue where my collections aren't automatically syncing. For example, I add a new paper to a collection, but it doesn't show up in Notion until I manually sync either that item or the whole collection (I do see the "Sync to Notion" option). I had Zutilo installed but have disabled it.

**Comment by grisaitis** [comment] 2023-05-06 17:25
I'm also experiencing sinking issues after updating tags on the web app (eg https://www.zotero.org/<username>/collections/********/item-list). 

How do I trigger a sync from the web app?

**Comment by dvanoni** [comment] 2023-05-06 18:09
Hi @grisaitis, unfortunately you can't trigger a sync from the web app. The Notero plugin only supports the desktop version of Zotero, so you'll have to open the Zotero desktop app in order to perform a sync to Notion.

**Comment by jmiss19** [comment] 2023-10-04 19:43
Hi @dvanoni unfortunately the "sync to Notion" option when I right-click on an item or a collection does not appear. I feel like I have tried everything in this thread from disable the Notion and LibreOffice Add-On to adding a notion tag manually... I have the newest version 0.4.13. 

These are the errors in the Error Console when I search for notion, hope that helps and you can figure out what's wrong! I love this plugin!
![Bild 04 10 23 um 21 41](https://github.com/dvanoni/notero/assets/146995505/8c428259-e537-411a-9258-7d8626f6c4ae)

**Comment by dvanoni** [comment] 2023-10-04 20:20
Hi @jmiss19, thanks for sharing that screenshot! It's super helpful.

That last message there points to the issue. I didn't realize it when I released the latest version of Notero, but it appears the `Zotero.getMainWindows` function referenced in that error is only available in the latest versions of Zotero.

I just tested on my Mac with the previous version of Zotero (6.0.26), and I encountered the same error as you. But if I use the latest version (6.0.27), it works as expected.

Can you try updating Zotero and see if that resolves the issue for you?

**Comment by jmiss19** [comment] 2023-10-05 11:44
It works now! Thanks for the quick help!

**Comment by dvanoni** [comment] 2023-12-28 06:24
Hi all, I've made some changes to the syncing functionality in recent versions of Notero, so I'm hoping this should resolve any issues you're still seeing. I'm going to close this for now, but please feel free to comment again if you're still having issues.

**Closed by dvanoni** 2023-12-28 06:24 UTC
