### ISSUE TITLE
there is no "notero preference" after I installed the edds-on of notero to zotero.

### ISSUE THREAD

**Issue by Olivia98106** [dvanoni/notero#315] opened 2023-08-14 14:24 UTC
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hashemd122** [comment] 2023-08-14 15:01
Same issue here
To reproduce: 
Launch zotero
go to tools
no notero preferences to be found.

**Comment by Sarahalkwai** [comment] 2023-08-14 20:39
I have the same issue. 
I tried restarting and reinstalling and everything but nothing worked.

**Comment by rbcwrtmp** [comment] 2023-08-14 22:18
Also had the same issue - I think it's a problem with the latest release; version 4.9 worked for me: https://github.com/dvanoni/notero/releases/tag/v0.4.9

**Comment by greystonegirl16** [comment] 2023-08-15 00:36
Same issue here - I've replicated the issue with my account on two different computers, and two of my classmates each have the same issue on their computers (so we've tried it on 4 computers, all have the same issue).

**Comment by dvanoni** [comment] 2023-08-15 02:15
Duplicate of #314

**Closed** 2023-08-15 06:40 UTC

**Comment by dvanoni** [comment] 2023-08-15 06:50
Hi y'all, sorry about this! Thanks for reporting it.

My latest upgrade of dependencies introduced a change that ended up crashing Notero as it started up. (See #317 if you're curious.)

This should be fixed in version [0.4.11](https://github.com/dvanoni/notero/releases/tag/v0.4.11).

**Comment by dvanoni** [comment] 2023-09-12 05:16
Hi @irissasara, thanks for reporting.

Would you mind sending me a screenshot of the Zotero logs by following these steps?

1. Restart Zotero.
2. Open the Error Console from the **Tools > Developer > Error Console** menu.
3. Scroll to the bottom of the Error Console.
4. Take a screenshot here. (We're looking for messages with `Notero` in them.)
