### ISSUE TITLE
Full citation loses formatting (ie. italics)

### ISSUE THREAD

**Issue by boothemjr** [dvanoni/notero#48] opened 2022-02-19 14:04 UTC
When materials are added, the citation loses its formatting, ie. italicization.

Citation in Notion after import: 

> Columbia University, USA, Lang, C., Siemens, G., University of Texas at Arlington, USA, Wise, A., New York University, USA, Gasevic, D., & University of Edinburgh, UK (Eds.). (2017). Handbook of Learning Analytics (First). Society for Learning Analytics Research (SoLAR). https://doi.org/10.18608/hla17

Citation from Zotero with "copy bibliography":

> Columbia University, USA, Lang, C., Siemens, G., University of Texas at Arlington, USA, Wise, A., New York University, USA, Gasevic, D., & University of Edinburgh, UK (Eds.). (2017). _Handbook of Learning Analytics_ (First). Society for Learning Analytics Research (SoLAR). [https://doi.org/10.18608/hla17](https://doi.org/10.18608/hla17)

**Comment by dvanoni** [comment] 2022-02-20 00:55
Hi @boothemjr, thanks for the feedback!

I'm going to close this issue as a duplicate of #17, but I'll add a link there pointing back here to the additional example you provided.

**Closed by dvanoni** 2022-02-20 00:55 UTC

**Comment by boothemjr** [comment] 2022-02-20 00:59
Thanks! I thought I had checked for the issue before but just have missed it.
