### ISSUE TITLE
Sync with multiple collections in Zotero?

### ISSUE THREAD

**Issue by linsharon** [dvanoni/notero#26] opened 2022-01-06 02:00 UTC
Hi,
I love this plugin. Thank you very much. At present it only allows synching with one collection inside Zotero. But very often a researcher will have multiple collections in the same library. Maybe it is possible to synch with multiple collections in the library? Good job! I look forward to new development of this plugin.

**Comment by theotheo** [comment] 2022-01-06 07:12
Hi, @linsharon. 
I think It's duplicate of this issue: https://github.com/dvanoni/notero/issues/6

**Comment by dvanoni** [comment] 2022-01-06 16:21
Hi @linsharon, thanks for the kind feedback! I'm glad you're enjoying the plugin!

I agree with @theotheo here and think this is a duplicate. I'm going to close this issue, but feel free to put a 👍 on #6!

**Closed by dvanoni** 2022-01-06 16:21 UTC
