### ISSUE TITLE
Allow to link different Zotero folders to different Notion databases

### ISSUE THREAD

**Issue by jankaWIS** [dvanoni/notero#276] opened 2023-06-18 08:22 UTC
**Is your feature request related to a problem? Please describe.**
It is both a feature and a problem.

**Describe the solution you'd like**
At the moment, I can create one link between the folders I select in Zotero (using `Tools -> Notero preferences`) and a database in Notion. I can create more databases in Notion and create connections, but I cannot link them to Zotero because there is only space for one integration (in the preferences window). I would like to be able to have different databases in Notion that are linked to specific folders (e.g., project related). Is there a way to do that? Maybe a workaround? Or can it be set up so that this can be done?

**Comment by dvanoni** [comment] 2023-06-18 19:10
Hi @jankaWIS, thanks for creating this request. I'm going to close it as a duplicate of #119, so please follow along with that issue.

For a workaround, you can use the `Collections` property in Notion to created filtered database views. Please see the discussion in #119 for more details.

**Closed by dvanoni** 2023-06-18 19:10 UTC
Labels: enhancement
