### ISSUE TITLE
Allow syncing for group libraries

### ISSUE THREAD

**Issue by Ph15** [dvanoni/notero#516] opened 2024-06-14 13:22 UTC
**Is your feature request related to a problem? Please describe.**
First of, thank you for making this connection possible!

I wanted to connect a group library with Notero, but it looks like Notero can only sync the main library.

**Describe the solution you'd like**
When I choose the collections to be synced in Notero preferences, I would like to see the group libraries that I contribute to, for them to be synced with Notion.

**Describe alternatives you've considered**
Create another account to edit the group library as my main library, but this would mean losing the ability to co-edit the library, plus lose access to my main library.

**Additional context**
![Options](https://github.com/dvanoni/notero/assets/11819455/f95591ea-b604-47f3-bec2-06538f1efb5d)

**Comment by dvanoni** [comment] 2024-06-15 15:41
Hi @Ph15, please see the discussion in #109. I believe syncing of group libraries is currently possible, but you need to have a collection (folder) in the group library in order to be able to select it for syncing.

![CleanShot 2024-06-15 at 08 40 02@2x](https://github.com/dvanoni/notero/assets/299357/2f75833a-e5ba-4dd9-a168-3df7c9cc2e4d)

Unfortunately, Notero doesn't provide a clear distinction between collections in your main library and collections in group libraries, so it's hard to tell which ones are which. I'd like to improve this and also allow syncing of an entire group library (not just collections).

Please follow #109 for future updates. Thanks!

**Comment by dvanoni** [comment] 2024-06-15 15:42
Duplicate of #109

**Closed by dvanoni** 2024-06-15 15:42 UTC
Labels: enhancement
