### ISSUE TITLE
Notion page with direct link to Zotero Item

### ISSUE THREAD

**Issue by davidxicota** [dvanoni/notero#123] opened 2022-08-31 18:46 UTC
Hi!

It would be great to add a field in the database with direct access to the Zotero item. So when clicked it directly opens the Zotero app with the file.
Or the finder app in Mac just to double click the file.

Seems that there has been some progress on having a zotero://<relative path> linking scheme.
https://zoteromusings.wordpress.com/2013/04/23/zotero-item-uris-from-client/

Thanks!

**Comment by dvanoni** [comment] 2022-09-02 04:11
Hi @davidxicota, thanks for reaching out!

It sounds like this might be a duplicate of #9 and #78. I agree that it'd be nice to support these features, but there are some limitations with Notion that prevent us from doing so easily. See the discussions on those other issues for some possible workarounds. Let me know if there's something there that might work for you.

**Comment by dvanoni** [comment] 2022-11-13 01:34
Duplicate of #78

**Closed** 2022-11-13 01:34 UTC
Labels: enhancement
