### ISSUE TITLE
"Book Section" items not 

### ISSUE THREAD

**Issue by numedhonning** [dvanoni/notero#86] opened 2022-06-10 14:34 UTC
Hi,

First of all thank you s much for doing this! I've been waiting for this plugin ever since I learned about Notion!

I noticed that the database works well with all articles and books, but "Book Section" items (chapters in books) as well as some other items (websites, "tidsskriftsartikler" - sorry, I don't know the english name for that but some kind of article) don't seem to work. Only "Item Type", "Name" and "Zotero URI" are filled out, all the other properties are blank. And yes, I checked, in Zotero they're not blank ;)
So it looks like this:

<img width="896" alt="Notero" src="https://user-images.githubusercontent.com/107262918/173088648-7e300ea1-d844-4de6-bc2e-faf6c6a55270.png">

It would be wonderful if the properties for this kind of items would work just like other items, as I use particular Book Sections quite a lot in my studies.

And again, thank you so much for your work!

**Comment by dvanoni** [comment] 2022-06-10 22:33
@numedhonning thanks for sharing this issue!

I notice the names of some of the properties in your screenshot are in a language other than English, and I believe Notero might not sync correctly because of that. Out of curiosity, did you happen to change the names of those properties _after_ you had already synced some items? If so, I wonder if the issue is caused by the property names in Notion rather than the item types in Zotero?

**Comment by Kitty-Zhu** [comment] 2022-06-12 14:48
> @numedhonning thanks for sharing this issue!
> 
> I notice the names of some of the properties in your screenshot are in a language other than English, and I believe Notero might not sync correctly because of that. Out of curiosity, did you happen to change the names of those properties _after_ you had already synced some items? If so, I wonder if the issue is caused by the property names in Notion rather than the item types in Zotero?

Hi, thanks for Notero sharing. I met a similar problem. I get blank in DOI, URL, and Zotero URL. My properties are in English while Zotero was automatically set up as Chinese. I haven't figured out how to change the language setting of my Zotero. However, since other items such as "Year" and "Title" are filled in, I guess it's not the problem of Zotero language?
![微信图片_20220612224758](https://user-images.githubusercontent.com/107357929/173238851-a08073a0-2264-45bf-8672-5d26e835016c.png)

**Comment by dvanoni** [comment] 2022-06-12 19:47
@Kitty-Zhu I have a hunch about the `DOI` and `URL` properties. In your screenshot, it looks like they're configured as **Files & media** properties instead of **URL** properties. If you change the types of those properties to **URL,** does that fix the issue?

As for the `Zotero URI` field, I'm not entirely sure why it's not working. I noticed in your message that you wrote `Zotero URL` instead of `Zotero URI` (note the difference betwen `URL` and `URI`). It's truncated in the screenshot, so I can't tell how it's spelled, but you'll want to make sure it's `Zotero URI` so it matches what Notero expects. Does that happen to be the issue?

**Comment by dvanoni** [comment] 2023-12-23 07:26
Duplicate of #355

**Closed by dvanoni** 2023-12-23 07:26 UTC
Labels: enhancement
