### ISSUE TITLE
Can connected with multi database?

### ISSUE THREAD

**Issue by ccwanggl** [dvanoni/notero#287] opened 2023-07-03 07:44 UTC
Hi, notero is a great zotero plugin, i wonder if it can connected with multi database. usually i need to tracking multi research feild, i wan't mixed those info together.

**Comment by dvanoni** [comment] 2023-07-04 18:23
Hi @ccwanggl! I do hope to add support for multiple databases in the future. Please follow along with #119 for progress updates and a possible temporary workaround.

**Comment by dvanoni** [comment] 2023-07-04 18:24
Duplicate of #119

**Closed** 2023-07-04 18:24 UTC
Labels: enhancement
