### ISSUE TITLE
Sync Images in Notes

### ISSUE THREAD

**Issue by richardkaplan** [dvanoni/notero#474] opened 2024-02-26 09:00 UTC
Syncing of notes is extremely useful as implemented.  

However I often clip an image from a publilcation - typically a Figure which cannot be copied/pasted as text.

These images work well in the Notes field in Zotero.  But the sync to Notion only syncs text.

Is it possible to also sync images from Notes?

**Comment by dvanoni** [comment] 2024-02-26 22:21
Hi @richardkaplan, unfortunately the Notion API does not yet support uploading files, so there's not an easy way to achieve this. Please see #385 for more info.

**Comment by dvanoni** [comment] 2024-02-26 22:21
Duplicate of #385

**Closed by dvanoni** 2024-02-26 22:21 UTC
Labels: enhancement
