### ISSUE TITLE
TypeError: this.itemProgress.setlcon is not a function

### ISSUE THREAD

**Issue by Panda-Kill** [dvanoni/notero#500] opened 2024-05-03 07:25 UTC
**Describe the issue**
When I click "Sync to Notion", here will pop up a notice saying "Syncing items to Notion... TypeError: this.itemProgress.setlcon is not a function. However, it actually sync to Notion successfully, so I am not sure what this notice impacts indeed.

**To Reproduce**

1. Right click an item
2. Click on 'Sync to Notion'
3. See error

**Expected behavior**
Since it says Error, I assume it shouldn't pop up normally.

**Screenshots**
![image](https://github.com/dvanoni/notero/assets/49262952/6bfe0db2-fd44-4fbe-8a1c-f28d6fca307d)

**Comment by WrongBobby** [comment] 2024-05-03 11:20
This is just to confirm that the same error occurs for me.

**Comment by Panda-Kill** [comment] 2024-05-03 11:23
Not sure if it may be related to any other plugins I am using. Just in case, I am using Green Frog, Zotero One and Translate for Zotero.

**Comment by dvanoni** [comment] 2024-05-03 20:09
Thanks for reporting this! What version of Zotero are you on?

**Comment by dvanoni** [comment] 2024-05-04 02:35
I was able to reproduce the error in Zotero 7.0.0-beta.77. It looks like the Zotero team introduced some breaking changes to the progress window last week in https://github.com/zotero/zotero/pull/4047. I'll work on a fix for this.

**Closed** 2024-05-04 06:41 UTC
Labels: bug

**Comment by dvanoni** [comment] 2024-05-04 06:47
Should be fixed in Notero [v0.5.16](https://github.com/dvanoni/notero/releases/tag/v0.5.16)!

**Comment by Panda-Kill** [comment] 2024-05-04 06:48
> Should be fixed in Notero [v0.5.16](https://github.com/dvanoni/notero/releases/tag/v0.5.16)!

Thank you very much! 😊
